### ISSUE TITLE
Add info in the readme

### ISSUE THREAD

**Issue by melonmouse** [status-hub/monitor#44]
This project was the top result when searching for "status" on the github marketplace. If it does what I think it does, I would be interested in using it! However, right now, the readme does not contain any info.
- What does status-hub/monitor do?
- How to use it?
- How does it compare to similar actions?
etc.

P.S. great that you are creating an action under the MIT license :D

**Comment by mauro-balades** [comment]
Sorry for not replying, I left this project away. I am planning on finishing it.
